In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Dense

In [3]:
data=load_breast_cancer()

In [4]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [48]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
data['data'].shape

(569, 30)

In [7]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [8]:
data['data'][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [9]:
j=0
for i in data['feature_names']:
  print(i,':',data['data'][0][j])
  j+=1

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


In [10]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [11]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [49]:
data['filename']

'breast_cancer.csv'

In [51]:
feature=data['data']

In [52]:
label=data['target']

In [15]:
feature.shape


(569, 30)

In [53]:
label.shape

(569,)

In [17]:
scale= StandardScaler()

feature= scale.fit_transform(feature)

In [18]:
j=0
for i in data['feature_names']:
  print(i,':',feature[0][j])
  j+=1

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [19]:
print(feature[0])
print(data['target_names'][label[0]])

[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]
malignant


In [20]:
df_frt=pd.DataFrame(feature, columns= data['feature_names'])
df_lbl=pd.DataFrame(label, columns= ['label'])
df=pd.concat([df_frt,df_lbl], axis=1)
df= df.sample(frac=1)

In [21]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
493    -0.473535     -1.503204       -0.541199  -0.505082        -1.611206   
356    -0.305966     -0.162813       -0.283349  -0.406391         0.842579   
52     -0.621222     -0.244260       -0.669713  -0.617993        -0.978545   
352     3.295334     -0.425771        3.387110   3.854074         1.319387   
456    -0.709266      2.327149       -0.704313  -0.681985        -0.198572   
..           ...           ...             ...        ...              ...   
495     0.210940      0.214172        0.170979   0.073978        -0.034891   
117     0.210940     -0.609610        0.274778   0.078528         1.411902   
249    -0.740508     -1.014519       -0.745503  -0.707013         0.351537   
12      1.432201      1.282296        1.665360   1.331355         0.073992   
137    -0.766069     -0.907474       -0.778867  -0.725500         0.002115   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
493         -1.211208       -1.024816            -0.965447      -0.725145   
356          0.493857        0.090781             0.183417       0.815553   
52          -1.077031       -0.867289            -0.913859       0.205845   
352          2.500819        3.113641             3.672569       0.527128   
456         -0.352516       -0.215937            -0.741555      -0.046070   
..                ...             ...                  ...            ...   
495         -0.395915       -0.258122             0.015240      -1.185164   
117          1.147683        1.006917             1.039777       1.260968   
249         -0.497685       -0.571494            -0.506314       0.260609   
12           2.680858        1.477729             1.621948       2.137194   
137         -0.671849       -0.675072            -0.520243      -0.283381   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
493               -0.378161  ...      -1.517252        -0.715492   -0.609263   
356                0.313629  ...      -0.134708        -0.388443   -0.508710   
52                -0.240654  ...      -0.707918        -0.702684   -0.621217   
352               -0.225060  ...      -0.341520         3.635028    4.137101   
456               -0.161268  ...       2.138591        -0.632092   -0.620162   
..                      ...  ...            ...              ...         ...   
495               -0.753827  ...       0.456415        -0.100117   -0.170488   
117                0.692130  ...       0.275658         0.590915    0.376926   
249               -0.158433  ...      -0.730716        -0.785787   -0.683447   
12                 2.155097  ...       0.694167         1.323647    0.793551   
137               -0.587967  ...      -0.595556        -0.814083   -0.735833   

     worst smoothness  worst compactness  worst concavity  \
493         -1.664826          -1.205453        -1.225520   
356          0.084665           0.073378        -0.071428   
52          -0.787669          -1.050935        -0.864315   
352          0.904396           2.159281         1.789052   
456          0.360831          -0.325481         0.096485   
..                ...                ...              ...   
495         -0.472051          -0.734519        -0.490252   
117          2.429885           1.232425         0.950924   
249          0.286310          -0.611108        -0.440357   
12          -1.256713           0.865372         0.439988   
137         -0.586024          -0.569123        -0.634657   

     worst concave points  worst symmetry  worst fractal dimension  label  
493             -1.336990       -1.004247                -0.757302      1  
356              0.170443        0.343365                -0.042993      1  
52              -0.786396       -0.187267                -0.546722      1  
352              2.451387        1.276824                 0.232978      0  
456             -0.704325       -0.027107                -0.650904   

In [22]:
#500 Training
x_train = feature[:500]
y_train = label[:500]

#35 Validation
x_val = feature[500:535]
y_val = label[500:535]

#34 Testing
x_test = feature[535:]
y_test = label[535:]

In [23]:
x_train.shape

(500, 30)

In [45]:
from keras.backend import binary_crossentropy
model=Sequential()
model.add(Dense(50, activation='relu', input_dim= 30))
model.add(Dense(40, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(34, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'] )

In [46]:
model.fit(x_train, y_train, batch_size=1, epochs=10, validation_data=(x_val, y_val))

Epoch 1/10
500/500 [==============================] - 2s 3ms/step - loss: 0.1986 - accuracy: 0.9160 - val_loss: 0.0548 - val_accuracy: 0.9714
Epoch 2/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0714 - accuracy: 0.9720 - val_loss: 0.1040 - val_accuracy: 0.9714
Epoch 3/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0473 - accuracy: 0.9860 - val_loss: 0.0563 - val_accuracy: 0.9714
Epoch 4/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0535 - accuracy: 0.9820 - val_loss: 0.0703 - val_accuracy: 0.9429
Epoch 5/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0478 - accuracy: 0.9880 - val_loss: 0.0653 - val_accuracy: 0.9714
Epoch 6/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0339 - accuracy: 0.9880 - val_loss: 0.1239 - val_accuracy: 0.9714
Epoch 7/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0492 - accuracy: 0.9840 - val_loss: 0.1397 - val_accuracy: 0.9714
Epoch 

In [26]:
x_train[0]

array([ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
        3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
        2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
        1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
        1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
        2.61666502,  2.10952635,  2.29607613,  2.75062224,  1.93701461])

In [47]:
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.0759 - accuracy: 0.9706


[0.07585251331329346, 0.970588207244873]

In [28]:
y_test

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [29]:
y_val

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [30]:
sample= x_test[10]

In [31]:
sample.shape

(30,)

In [32]:
sample


array([-0.14407806,  0.91694624, -0.19684934, -0.23233219, -0.27756523,
       -0.6987597 , -0.741488  , -0.6316726 , -0.53894726, -0.67869351,
       -0.21356438,  0.21617286, -0.39605381, -0.20015129, -0.39100882,
       -0.25084001, -0.38739725, -0.44317904,  0.03967757, -0.45840426,
       -0.19034815,  0.55574951, -0.28836304, -0.26506358, -0.47205092,
       -0.65245698, -0.80257043, -0.65270672, -0.41860997, -0.7988643 ])

In [33]:
for i in range(30):
  sample=x_test[i]
  sample=np.reshape(sample,(1,30))

  if model.predict(sample)[0][0] >0.5 :
    print("-Benign")
  else:
    print("-Malignant")

  if y_test[i]==1:
    print("*Benign")
  else:
    print("*Malignant")  

  print("------")  

-Malignant
*Malignant
------
-Malignant
*Malignant
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Malignant
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Malignant
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Benign
*Benign
------
-Malignant
*Malignant
------
-Malignant
*Malignant
------
-Malignant
*Malignant
------


In [34]:
sample.shape

(1, 30)

In [35]:
model.predict(sample)

array([[3.0691517e-18]], dtype=float32)

In [36]:
x_test[0]

array([ 1.82414032,  0.36543133,  1.88778669,  1.85751441,  0.58638323,
        1.31824626,  1.50283863,  2.14814488,  1.15143953, -0.04077169,
        1.05904307, -0.4114087 ,  0.910827  ,  1.04382537, -0.82102626,
        0.03810891,  0.27043808,  0.3915519 , -0.12862155, -0.41830962,
        1.66304049, -0.03211657,  1.57682617,  1.63207582, -0.24410428,
        0.37681708,  0.82091153,  1.5256103 ,  0.28512459, -0.45750286])

In [37]:
y_test[0]

0

In [38]:
x_test[10]

array([-0.14407806,  0.91694624, -0.19684934, -0.23233219, -0.27756523,
       -0.6987597 , -0.741488  , -0.6316726 , -0.53894726, -0.67869351,
       -0.21356438,  0.21617286, -0.39605381, -0.20015129, -0.39100882,
       -0.25084001, -0.38739725, -0.44317904,  0.03967757, -0.45840426,
       -0.19034815,  0.55574951, -0.28836304, -0.26506358, -0.47205092,
       -0.65245698, -0.80257043, -0.65270672, -0.41860997, -0.7988643 ])

In [39]:
y_test[10]

1